export const doctorPerfilStrings = {
  loading: "Cargando perfil...",
  loadError: "No se pudo cargar el perfil.",
  updateSuccess: "Perfil actualizado correctamente.",
  updateError: "No se pudo actualizar el perfil. Intenta de nuevo.",
  memberSincePrefix: "Médico desde",
  verified: "Verificado",
  pendingSep: "Pendiente SEP",
  accountInfo: "Información de cuenta",
  email: "Correo electrónico",
  doctorId: "ID de médico",
  professionalInfo: "Información profesional",
  edit: "Editar",
  cancel: "Cancelar",
  save: "Guardar cambios",
  saving: "Guardando...",
  license: "Cédula profesional",
  licensePlaceholder: "Ej. 12345678",
  speciality: "Especialidad",
  specialityPlaceholder: "Ej. Endocrinología",
  notRegistered: "No registrada",
} as const;
