export const registroDiarioStrings = {
  nuevoTitle: "Nuevo Registro",
  fecha: "Fecha",
  glucosaAntes: "Glucosa Antes",
  glucosaDespues: "Glucosa Después (2h)",
  hcConsumidos: "HC Consumidos",
  dosisAplicada: "Dosis Aplicada",
  queComiste: "¿Qué comiste?",
  queComistePlaceholder: "Ej. 2 rebanadas de pan...",
  comoSentiste: "¿Cómo te sentiste?",
  comoSentistePlaceholder: "Breve nota...",
  guardar: "Guardar Registro",
  guardando: "Guardando...",
  historialTitle: "Historial de Registros",
  colFecha: "Fecha",
  colAntes: "Antes",
  colDespues: "Después",
  colHc: "HC (g)",
  colDosis: "Dosis (U)",
  emptyPeriodo: "No hay registros en este periodo",
  confirmDelete: "¿Eliminar este registro?",
  guardadoOk: "Registro guardado exitosamente",
  guardadoError: "Error al guardar el registro",
  eliminadoOk: "Registro eliminado",
  eliminadoError: "Error al eliminar",
} as const;
