import { PatientProfileDto, HealthRecordDto } from '../patient/types';

export const MOCK_DOCTOR_ID = "dr-alexander-thorne-001";
export const MOCK_PATIENT_ID = "pt-sarah-jenkins-001";

export const initialPatients: PatientProfileDto[] = [
  {
    id: MOCK_PATIENT_ID,
    firstName: "Sarah",
    lastName: "Jenkins",
    dateOfBirth: "1978-05-14T00:00:00Z",
    gender: "F",
    diabetesType: "Tipo 2",
    heightCm: 165,
    weightKg: 78.5,
    pregnancyStatus: false,
    assignedDoctorId: MOCK_DOCTOR_ID,
  },
  {
    id: "pt-michael-chang-002",
    firstName: "Michael",
    lastName: "Chang",
    dateOfBirth: "1965-11-22T00:00:00Z",
    gender: "M",
    diabetesType: "Tipo 1",
    heightCm: 178,
    weightKg: 82.0,
    pregnancyStatus: false,
    assignedDoctorId: MOCK_DOCTOR_ID,
  },
  {
    id: "pt-emily-rose-003",
    firstName: "Emily",
    lastName: "Rose",
    dateOfBirth: "1992-03-10T00:00:00Z",
    gender: "F",
    diabetesType: "Prediabetes",
    heightCm: 160,
    weightKg: 64.0,
    pregnancyStatus: true,
    assignedDoctorId: MOCK_DOCTOR_ID,
  }
];

export const initialRecords: HealthRecordDto[] = [
  // ── Sarah Jenkins (DM2) — 9 días: 2026-05-13 al 2026-05-21 ──────────────
  {
    id: "rec-s-007",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-21T07:30:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",             valor: 135, hora: "07:30", alimentos: null },
      { tipo: "despues_desayuno",  valor: 185, hora: "09:30", alimentos: "Tamales con atole" },
      { tipo: "despues_comida",    valor: 158, hora: "15:00", alimentos: "Caldo de pollo con verduras" },
    ],
    presion_sistolica: 140,
    presion_diastolica: 88,
    frecuencia_cardiaca: 84,
    peso: 78.5,
    cintura: 92,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Tuve un antojo anoche, comí más de lo que debía.",
  },
  {
    id: "rec-s-006",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-20T07:45:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 125, hora: "07:45", alimentos: null },
      { tipo: "despues_desayuno", valor: 172, hora: "09:45", alimentos: "Huevos a la mexicana, tortillas" },
      { tipo: "despues_cena",     valor: 148, hora: "21:30", alimentos: "Sopa de fideo" },
    ],
    presion_sistolica: 132,
    presion_diastolica: 84,
    frecuencia_cardiaca: 78,
    peso: 78.7,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Caminé 30 minutos por la tarde. Me sentí bien.",
  },
  {
    id: "rec-s-005",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-19T08:00:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",           valor: 118, hora: "08:00", alimentos: null },
      { tipo: "antes_comida",    valor: 110, hora: "13:30", alimentos: null },
      { tipo: "despues_comida",  valor: 162, hora: "15:30", alimentos: "Pollo asado, ensalada, 2 tortillas" },
    ],
    presion_sistolica: 128,
    presion_diastolica: 80,
    frecuencia_cardiaca: 76,
    peso: 78.5,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Tomé todos mis medicamentos. Dieta controlada.",
  },
  {
    id: "rec-s-004",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-18T07:30:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 130, hora: "07:30", alimentos: null },
      { tipo: "despues_desayuno", valor: 178, hora: "09:30", alimentos: "Cereal con leche y fruta" },
      { tipo: "despues_cena",     valor: 150, hora: "21:00", alimentos: "Frijoles con queso y tortillas" },
    ],
    presion_sistolica: 135,
    presion_diastolica: 86,
    frecuencia_cardiaca: 80,
    peso: 79.0,
    cintura: 92,
    imc: null,
    hba1c: 7.4,
    colesterol_total: 205,
    colesterol_ldl: 125,
    colesterol_hdl: 44,
    trigliceridos: 170,
    bun: 16,
    creatinina: 1.0,
    ego_proteinas: "trazas",
    ego_glucosa: "0",
    notas: "Día de laboratorio. Resultados entregados al Dr. Thorne.",
  },
  {
    id: "rec-s-003",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-17T08:15:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 148, hora: "08:15", alimentos: null },
      { tipo: "despues_desayuno", valor: 198, hora: "10:15", alimentos: "Pan dulce y café con azúcar" },
      { tipo: "despues_comida",   valor: 182, hora: "15:30", alimentos: "Tacos de canasta" },
    ],
    presion_sistolica: 152,
    presion_diastolica: 96,
    frecuencia_cardiaca: 90,
    peso: 79.2,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Olvidé el medicamento de la mañana. Mucho estrés en el trabajo. Dolor de cabeza.",
  },
  {
    id: "rec-s-002",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-16T07:00:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 122, hora: "07:00", alimentos: null },
      { tipo: "despues_desayuno", valor: 165, hora: "09:00", alimentos: "Avena con canela sin azúcar" },
      { tipo: "antes_cena",       valor: 130, hora: "19:30", alimentos: null },
    ],
    presion_sistolica: 130,
    presion_diastolica: 82,
    frecuencia_cardiaca: 77,
    peso: 78.8,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Día tranquilo. Dieta controlada. Ejercicio leve.",
  },
  {
    id: "rec-s-001",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-15T07:45:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 142, hora: "07:45", alimentos: null },
      { tipo: "despues_desayuno", valor: 188, hora: "09:45", alimentos: "Huevos fritos, frijoles y jugo de naranja" },
      { tipo: "despues_comida",   valor: 170, hora: "15:00", alimentos: "Arroz rojo con pollo y refresco" },
    ],
    presion_sistolica: 145,
    presion_diastolica: 90,
    frecuencia_cardiaca: 88,
    peso: 79.5,
    cintura: 93,
    imc: null,
    hba1c: 7.8,
    colesterol_total: 215,
    colesterol_ldl: 135,
    colesterol_hdl: 42,
    trigliceridos: 185,
    bun: 18,
    creatinina: 1.1,
    ego_proteinas: "trazas",
    ego_glucosa: "+1",
    notas: "Control de base. El Dr. ajustó la dosis de Metformina a 1000mg.",
  },

  {
    id: "rec-s-009",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-14T07:15:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 138, hora: "07:15", alimentos: null },
      { tipo: "despues_desayuno", valor: 182, hora: "09:15", alimentos: "Chilaquiles con crema y frijoles" },
      { tipo: "antes_comida",     valor: 115, hora: "13:00", alimentos: null },
      { tipo: "despues_comida",   valor: 174, hora: "15:00", alimentos: "Carne asada, arroz y ensalada" },
      { tipo: "despues_cena",     valor: 145, hora: "21:30", alimentos: "Tlayuda con frijoles y tasajo" },
    ],
    presion_sistolica: 138,
    presion_diastolica: 86,
    frecuencia_cardiaca: 82,
    peso: 79.3,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Fui a un evento familiar. Comí más de lo habitual.",
  },
  {
    id: "rec-s-008",
    patientId: MOCK_PATIENT_ID,
    timestamp: "2026-05-13T08:00:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 120, hora: "08:00", alimentos: null },
      { tipo: "despues_desayuno", valor: 160, hora: "10:00", alimentos: "Yogurt con granola y fruta" },
      { tipo: "antes_comida",     valor: 108, hora: "13:30", alimentos: null },
      { tipo: "despues_comida",   valor: 155, hora: "15:30", alimentos: "Sopa de lentejas, pollo y 1 tortilla" },
      { tipo: "despues_cena",     valor: 138, hora: "21:00", alimentos: "Verduras salteadas con queso" },
    ],
    presion_sistolica: 126,
    presion_diastolica: 80,
    frecuencia_cardiaca: 74,
    peso: 79.1,
    cintura: null,
    imc: null,
    hba1c: null,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: null,
    ego_glucosa: null,
    notas: "Buen día. Caminata de 20 minutos. Tomé todos los medicamentos.",
  },

  // ── Michael Chang (DM1) — Buen control ──────────────────────────────────
  {
    id: "rec-m-001",
    patientId: "pt-michael-chang-002",
    timestamp: "2026-05-21T06:30:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",            valor: 92,  hora: "06:30", alimentos: null },
      { tipo: "despues_desayuno", valor: 128, hora: "08:30", alimentos: "Tostada integral con huevo revuelto" },
      { tipo: "despues_comida",   valor: 112, hora: "14:30", alimentos: "Pescado con vegetales al vapor" },
      { tipo: "despues_cena",     valor: 105, hora: "21:00", alimentos: "Ensalada con proteína" },
    ],
    presion_sistolica: 118,
    presion_diastolica: 76,
    frecuencia_cardiaca: 70,
    peso: 82.0,
    cintura: 89,
    imc: null,
    hba1c: 6.2,
    colesterol_total: 158,
    colesterol_ldl: 92,
    colesterol_hdl: 58,
    trigliceridos: 105,
    bun: 13,
    creatinina: 0.9,
    ego_proteinas: "negativo",
    ego_glucosa: "0",
    notas: "Excelente control. Novolog 5u antes de cada comida. Lantus 18u nocturna.",
  },

  // ── Emily Rose (Prediabetes, embarazo) ──────────────────────────────────
  {
    id: "rec-e-001",
    patientId: "pt-emily-rose-003",
    timestamp: "2026-05-21T08:00:00.000Z",
    glucosas_comidas: [
      { tipo: "ayuno",           valor: 98,  hora: "08:00", alimentos: null },
      { tipo: "despues_desayuno", valor: 132, hora: "10:00", alimentos: "Fruta con yogurt natural" },
    ],
    presion_sistolica: 112,
    presion_diastolica: 70,
    frecuencia_cardiaca: 82,
    peso: 64.5,
    cintura: 82,
    imc: null,
    hba1c: 5.9,
    colesterol_total: null,
    colesterol_ldl: null,
    colesterol_hdl: null,
    trigliceridos: null,
    bun: null,
    creatinina: null,
    ego_proteinas: "negativo",
    ego_glucosa: "0",
    notas: "Semana 18 de embarazo. Sin síntomas de alarma.",
  },
];
