import { NextResponse } from 'next/server';

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 400));

  const registros = [
    {
      id: "reg-007",
      fecha: "2026-05-21",
      glucosa_ayuno: 135,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 135, hora: "07:30", alimentos: null },
        { tipo: "despues_desayuno", valor: 185, hora: "09:30", alimentos: "Tamales con atole" },
        { tipo: "despues_comida",   valor: 158, hora: "15:00", alimentos: "Caldo de pollo con verduras" },
      ],
      presion_sistolica: 140,
      presion_diastolica: 88,
      frecuencia_cardiaca: 84,
      peso: 78.5,
      cintura: 92,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Tuve un antojo anoche, comí más de lo que debía.",
    },
    {
      id: "reg-006",
      fecha: "2026-05-20",
      glucosa_ayuno: 125,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 125, hora: "07:45", alimentos: null },
        { tipo: "despues_desayuno", valor: 172, hora: "09:45", alimentos: "Huevos a la mexicana, tortillas" },
        { tipo: "despues_cena",     valor: 148, hora: "21:30", alimentos: "Sopa de fideo" },
      ],
      presion_sistolica: 132,
      presion_diastolica: 84,
      frecuencia_cardiaca: 78,
      peso: 78.7,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Caminé 30 minutos por la tarde. Me sentí bien.",
    },
    {
      id: "reg-005",
      fecha: "2026-05-19",
      glucosa_ayuno: 118,
      glucosas_comidas: [
        { tipo: "ayuno",          valor: 118, hora: "08:00", alimentos: null },
        { tipo: "antes_comida",   valor: 110, hora: "13:30", alimentos: null },
        { tipo: "despues_comida", valor: 162, hora: "15:30", alimentos: "Pollo asado, ensalada, 2 tortillas" },
      ],
      presion_sistolica: 128,
      presion_diastolica: 80,
      frecuencia_cardiaca: 76,
      peso: 78.5,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Tomé todos mis medicamentos. Dieta controlada.",
    },
    {
      id: "reg-004",
      fecha: "2026-05-18",
      glucosa_ayuno: 130,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 130, hora: "07:30", alimentos: null },
        { tipo: "despues_desayuno", valor: 178, hora: "09:30", alimentos: "Cereal con leche y fruta" },
        { tipo: "despues_cena",     valor: 150, hora: "21:00", alimentos: "Frijoles con queso y tortillas" },
      ],
      presion_sistolica: 135,
      presion_diastolica: 86,
      frecuencia_cardiaca: 80,
      peso: 79.0,
      cintura: 92,
      hba1c: 7.4,
      colesterol_total: 205,
      colesterol_ldl: 125,
      colesterol_hdl: 44,
      trigliceridos: 170,
      bun: 16,
      creatinina: 1.0,
      ego_proteinas: "trazas",
      ego_glucosa: "0",
      notas: "Día de laboratorio. Resultados entregados al Dr. Thorne.",
    },
    {
      id: "reg-003",
      fecha: "2026-05-17",
      glucosa_ayuno: 148,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 148, hora: "08:15", alimentos: null },
        { tipo: "despues_desayuno", valor: 198, hora: "10:15", alimentos: "Pan dulce y café con azúcar" },
        { tipo: "despues_comida",   valor: 182, hora: "15:30", alimentos: "Tacos de canasta" },
      ],
      presion_sistolica: 152,
      presion_diastolica: 96,
      frecuencia_cardiaca: 90,
      peso: 79.2,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Olvidé el medicamento de la mañana. Mucho estrés. Dolor de cabeza.",
    },
    {
      id: "reg-002",
      fecha: "2026-05-16",
      glucosa_ayuno: 122,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 122, hora: "07:00", alimentos: null },
        { tipo: "despues_desayuno", valor: 165, hora: "09:00", alimentos: "Avena con canela sin azúcar" },
        { tipo: "antes_cena",       valor: 130, hora: "19:30", alimentos: null },
      ],
      presion_sistolica: 130,
      presion_diastolica: 82,
      frecuencia_cardiaca: 77,
      peso: 78.8,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Día tranquilo. Dieta controlada. Ejercicio leve.",
    },
    {
      id: "reg-009",
      fecha: "2026-05-14",
      glucosa_ayuno: 138,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 138, hora: "07:15", alimentos: null },
        { tipo: "despues_desayuno", valor: 182, hora: "09:15", alimentos: "Chilaquiles con crema y frijoles" },
        { tipo: "antes_comida",     valor: 115, hora: "13:00", alimentos: null },
        { tipo: "despues_comida",   valor: 174, hora: "15:00", alimentos: "Carne asada, arroz y ensalada" },
        { tipo: "despues_cena",     valor: 145, hora: "21:30", alimentos: "Tlayuda con frijoles y tasajo" },
      ],
      presion_sistolica: 138,
      presion_diastolica: 86,
      frecuencia_cardiaca: 82,
      peso: 79.3,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Fui a un evento familiar. Comí más de lo habitual.",
    },
    {
      id: "reg-008",
      fecha: "2026-05-13",
      glucosa_ayuno: 120,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 120, hora: "08:00", alimentos: null },
        { tipo: "despues_desayuno", valor: 160, hora: "10:00", alimentos: "Yogurt con granola y fruta" },
        { tipo: "antes_comida",     valor: 108, hora: "13:30", alimentos: null },
        { tipo: "despues_comida",   valor: 155, hora: "15:30", alimentos: "Sopa de lentejas, pollo y 1 tortilla" },
        { tipo: "despues_cena",     valor: 138, hora: "21:00", alimentos: "Verduras salteadas con queso" },
      ],
      presion_sistolica: 126,
      presion_diastolica: 80,
      frecuencia_cardiaca: 74,
      peso: 79.1,
      cintura: null,
      hba1c: null,
      colesterol_total: null,
      colesterol_ldl: null,
      colesterol_hdl: null,
      trigliceridos: null,
      bun: null,
      creatinina: null,
      ego_proteinas: null,
      ego_glucosa: null,
      notas: "Buen día. Caminata de 20 minutos. Tomé todos los medicamentos.",
    },
    {
      id: "reg-001",
      fecha: "2026-05-15",
      glucosa_ayuno: 142,
      glucosas_comidas: [
        { tipo: "ayuno",            valor: 142, hora: "07:45", alimentos: null },
        { tipo: "despues_desayuno", valor: 188, hora: "09:45", alimentos: "Huevos fritos, frijoles y jugo de naranja" },
        { tipo: "despues_comida",   valor: 170, hora: "15:00", alimentos: "Arroz rojo con pollo y refresco" },
      ],
      presion_sistolica: 145,
      presion_diastolica: 90,
      frecuencia_cardiaca: 88,
      peso: 79.5,
      cintura: 93,
      hba1c: 7.8,
      colesterol_total: 215,
      colesterol_ldl: 135,
      colesterol_hdl: 42,
      trigliceridos: 185,
      bun: 18,
      creatinina: 1.1,
      ego_proteinas: "trazas",
      ego_glucosa: "+1",
      notas: "Control de base. El Dr. ajustó la dosis de Metformina a 1000mg.",
    },
  ];

  return NextResponse.json(registros);
}
